PPU.data3 <- Read10X(data.dir = "Y:/Andre scRNAseq/MK01_PP_U/outs/filtered_feature_bc_matrix/")
PPU.object3 <- CreateSeuratObject(counts = PPU.data3, project = "PPU823")
PPT.data3 <- Read10X(data.dir = "Y:/Andre scRNAseq/MK01_PP_T/outs/filtered_feature_bc_matrix/")
PPT.object3 <- CreateSeuratObject(counts = PPT.data3, project = "PPT823")
CMU.data3 <- Read10X(data.dir = "Y:/Andre scRNAseq/MK01_CM_U/outs/filtered_feature_bc_matrix/")
CMU.object3 <- CreateSeuratObject(counts = CMU.data3, project = "CMU823")
CMT.data3 <- Read10X(data.dir = "Y:/Andre scRNAseq/MK01_CM_T/outs/filtered_feature_bc_matrix/")
CMT.object3 <- CreateSeuratObject(counts = CMT.data3, project = "CMT823")
CPT.data3 <- Read10X(data.dir = "Y:/Andre scRNAseq/MK01_CP_T/outs/filtered_feature_bc_matrix/")
CPT.object3 <- CreateSeuratObject(counts = CPT.data3, project = "CPT823")
merge1 <- merge(PPU.object3, y = PPT.object3, add.cell.ids = c("PPU", "PPT"), project = "Me1823")
merge2 <- merge(CMU.object3, y = c(PPU.object3,PPT.object3), add.cell.ids = c("CMU","PPU", "PPT"), project = "Me2823")
merge2
View(merge2)
mergefin <- merge(CPT.object3, y = c(CMT.object3,CMU.object3,PPU.object3,PPT.object3), add.cell.ids = c("CPT","CMT","CMU","PPU", "PPT"), project = "Me3823")
View(mergefin)
unique(sapply(X = strsplit(colnames(mergefin), split = "_"), FUN = "[", 1))
table(mergefin$orig.ident)
save(mergefin, file = "Z:/Andre/RNA Seq Analysis CM/mergefinsamprawcountmtx.RData")
library(dplyr)
library(patchwork)
mergefin[["percent.mt"]] <- PercentageFeatureSet(mergefin, pattern = "^MT-")
VlnPlot(mergefin, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
mergefinnorm <- NormalizeData(mergefin, normalization.method = "LogNormalize", scale.factor = 10000)
mergefin <- NormalizeData(mergefin, normalization.method = "LogNormalize", scale.factor = 10000)
mergefin <- FindVariableFeatures(mergefin, selection.method = "vst", nfeatures = 2000)
all.genes <- rownames(mergefin)
mergefin <- ScaleData(mergefin, features = all.genes)
mergefin <- ScaleData(mergefin, features = all.genes)
mergefin <- ScaleData(mergefin)
mergefin <- RunPCA(mergefin, features = VariableFeatures(object = mergefin))
ElbowPlot(mergefin)
mergefin <- FindNeighbors(mergefin, dims = 1:15)
mergefin <- FindClusters(mergefin, resolution = 0.5)
mergefin <- RunUMAP(mergefin, dims = 1:15)
DimPlot(mergefin, reduction = "umap")
DimPlot(mergefin, group.by = "orig.ident")
saveRDS(mergefin, file = "Y:/Andre/RNA Seq Analysis CM/mergefinprocessed.rds")
saveRDS(mergefin, file = "Z:/Andre/RNA Seq Analysis CM/mergefinprocessed.rds")
mergefin@meta.data
mergefin@meta.data[["orig.ident"]]
logfc.data3 <- logFC(cluster.ids=mergefin@meta.data[["orig.ident"]],expr.mat=mergefin[["RNA"]]@counts)
library(devtools)
install_github("arc85/singleseqgset")
library(singleseqgset)
logfc.data3 <- logFC(cluster.ids=mergefin@meta.data[["orig.ident"]],expr.mat=mergefin[["RNA"]]@counts)
mergefin[["RNA"]]@counts